# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
  
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 11']
          xcode: ['/Applications/Xcode_12.5.app/Contents/Developer']
    #defaults:
      #run:
        #working-directory: ./POC-GithubActionsCache
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build and Test
      run: |
        xcodebuild clean test -project POC-GithubActionsCache.xcodeproj -scheme POC-GithubActionsCache -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        
      env: 
        destination: ${{ matrix.destination }}
